/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import database.ConnectionMaker;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JFrame;
import interfaces.myframes.AddDrugs;
import interfaces.myframes.AlternativeMed;
import interfaces.myframes.ClassifiesDrugs;
import interfaces.myframes.ComAndDesc;
import interfaces.myframes.Contradictions;
import interfaces.myframes.DeleteDrugs;
import interfaces.myframes.SearchById;
import interfaces.myframes.SideEffects;
import interfaces.myframes.UpdateDrugs;
import interfaces.myframes.ViewDrugs;
import interfaces.myframes.SearchByName;

/**
 *
 * @author besan
 */
public final class OptionsScreen extends javax.swing.JFrame {

   
    public OptionsScreen() {
        this.setTitle("Options Screen");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Point middle = new Point(screenSize.width/6 , screenSize.height /9);
        Point newLocation = new Point(middle.x - (this.getWidth()),middle.y - (this.getHeight())); 
        this.setLocation(newLocation);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        
              
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAddDrugs = new javax.swing.JMenu();
        jMenuItemAdd = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jMenuItemUpdate = new javax.swing.JMenuItem();
        jMenuItemView = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemSearchId = new javax.swing.JMenuItem();
        jMenuItemSearchName = new javax.swing.JMenuItem();
        jMenuDisplaysConflicts = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuComandDesc = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuAlternative = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuSideEffects = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Welcome ");

        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuBar1.setMargin(new java.awt.Insets(20, 0, 15, 0));

        jMenuAddDrugs.setForeground(new java.awt.Color(0, 153, 153));
        jMenuAddDrugs.setText("Drugs Manager    ");
        jMenuAddDrugs.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N

        jMenuItemAdd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        jMenuItemAdd.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemAdd.setText("Add Drugs");
        jMenuItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddActionPerformed(evt);
            }
        });
        jMenuAddDrugs.add(jMenuItemAdd);

        jMenuItemDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        jMenuItemDelete.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemDelete.setText("Delete Drugs");
        jMenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteActionPerformed(evt);
            }
        });
        jMenuAddDrugs.add(jMenuItemDelete);

        jMenuItemUpdate.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, 0));
        jMenuItemUpdate.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemUpdate.setText("Update Drugs");
        jMenuItemUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUpdateActionPerformed(evt);
            }
        });
        jMenuAddDrugs.add(jMenuItemUpdate);

        jMenuItemView.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, 0));
        jMenuItemView.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemView.setText("View Drugs");
        jMenuItemView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewActionPerformed(evt);
            }
        });
        jMenuAddDrugs.add(jMenuItemView);

        jMenuBar1.add(jMenuAddDrugs);

        jMenu2.setForeground(new java.awt.Color(0, 153, 153));
        jMenu2.setText("Classifies Drugs   ");
        jMenu2.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N
        jMenu2.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem1.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem1.setText("Classifies Drugs");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu4.setForeground(new java.awt.Color(0, 153, 153));
        jMenu4.setText("Search");
        jMenu4.setFont(new java.awt.Font("Yu Gothic Light", 1, 12)); // NOI18N

        jMenuItemSearchId.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, 0));
        jMenuItemSearchId.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemSearchId.setText("Search By Id");
        jMenuItemSearchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchIdActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemSearchId);

        jMenuItemSearchName.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, 0));
        jMenuItemSearchName.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItemSearchName.setText("Search By Name");
        jMenuItemSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSearchNameActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemSearchName);

        jMenuBar1.add(jMenu4);

        jMenuDisplaysConflicts.setForeground(new java.awt.Color(0, 153, 153));
        jMenuDisplaysConflicts.setText("  Displays Contradictions");
        jMenuDisplaysConflicts.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem2.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem2.setText("Displays Contradictions");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuDisplaysConflicts.add(jMenuItem2);

        jMenuBar1.add(jMenuDisplaysConflicts);

        jMenuComandDesc.setForeground(new java.awt.Color(0, 153, 153));
        jMenuComandDesc.setText("   Displays Composition and Describtion");
        jMenuComandDesc.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        jMenuItem3.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem3.setText("Displays Composition and Describtion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuComandDesc.add(jMenuItem3);

        jMenuBar1.add(jMenuComandDesc);

        jMenuAlternative.setForeground(new java.awt.Color(0, 153, 153));
        jMenuAlternative.setText("   Displays Alternative Medicine");
        jMenuAlternative.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        jMenuItem4.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem4.setText("Displays Alternative Medicine");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuAlternative.add(jMenuItem4);

        jMenuBar1.add(jMenuAlternative);

        jMenuSideEffects.setForeground(new java.awt.Color(0, 153, 153));
        jMenuSideEffects.setText("  Display Side Effects");
        jMenuSideEffects.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N

        jMenuItem5.setForeground(new java.awt.Color(0, 0, 153));
        jMenuItem5.setText("Display Side Effects");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuSideEffects.add(jMenuItem5);

        jMenuBar1.add(jMenuSideEffects);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 646, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void jMenuItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddActionPerformed
          
        AddDrugs a = new AddDrugs();
        jDesktopPane1.add(a);
        a.setVisible(true);
     
    }//GEN-LAST:event_jMenuItemAddActionPerformed

    private void jMenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteActionPerformed
       
        DeleteDrugs a = new DeleteDrugs();
        jDesktopPane1.add(a);
        a.setVisible(true);

    }//GEN-LAST:event_jMenuItemDeleteActionPerformed

    private void jMenuItemUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUpdateActionPerformed
        UpdateDrugs a = new UpdateDrugs();
        jDesktopPane1.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItemUpdateActionPerformed

    private void jMenuItemViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewActionPerformed
       ViewDrugs a = new ViewDrugs();
        jDesktopPane1.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItemViewActionPerformed

    private void jMenuItemSearchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchIdActionPerformed
        SearchById a = new SearchById();
        jDesktopPane1.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItemSearchIdActionPerformed

    private void jMenuItemSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSearchNameActionPerformed
       SearchByName a = new SearchByName();
       jDesktopPane1.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItemSearchNameActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       ClassifiesDrugs a = new ClassifiesDrugs();
       jDesktopPane1.add(a);
        a.setVisible(true);    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new Logout().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Contradictions a = new Contradictions();
        jDesktopPane1.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ComAndDesc a = new ComAndDesc();
        jDesktopPane1.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        AlternativeMed a = new AlternativeMed();
        jDesktopPane1.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        SideEffects a = new SideEffects();
        jDesktopPane1.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {               
               new OptionsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAddDrugs;
    private javax.swing.JMenu jMenuAlternative;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuComandDesc;
    private javax.swing.JMenu jMenuDisplaysConflicts;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemAdd;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenuItem jMenuItemSearchId;
    private javax.swing.JMenuItem jMenuItemSearchName;
    private javax.swing.JMenuItem jMenuItemUpdate;
    private javax.swing.JMenuItem jMenuItemView;
    private javax.swing.JMenu jMenuSideEffects;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
