/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.myframes;

import database.ConnectionMaker;
import javax.swing.JOptionPane;
import database.DBDrugs;
import drugs.Drugs;

/**........................
 *
 * @author besan
 */
public class AddDrugs extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddDrugs
     */
    public AddDrugs() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelAlternative = new javax.swing.JLabel();
        jLabelSideEffects = new javax.swing.JLabel();
        jLabelDescAndComp = new javax.swing.JLabel();
        jTextFieldSideEffects = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldAlternative = new javax.swing.JTextField();
        jButtonAddDrug = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescribtion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabelSideEffects1 = new javax.swing.JLabel();
        jTextFieldBodyOrgans = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        setClosable(true);
        setTitle("Add Drugs");
        setToolTipText("Add Drugs");

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Name of Drug");

        jLabelAlternative.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabelAlternative.setForeground(new java.awt.Color(0, 153, 153));
        jLabelAlternative.setText("Alternative Medicine");

        jLabelSideEffects.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabelSideEffects.setForeground(new java.awt.Color(0, 153, 153));
        jLabelSideEffects.setText("Side Effects");

        jLabelDescAndComp.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabelDescAndComp.setForeground(new java.awt.Color(0, 153, 153));
        jLabelDescAndComp.setText("Describtion and Composition");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jButtonAddDrug.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        jButtonAddDrug.setForeground(new java.awt.Color(0, 0, 153));
        jButtonAddDrug.setText("Add");
        jButtonAddDrug.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 51)));
        jButtonAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDrugActionPerformed(evt);
            }
        });

        jTextAreaDescribtion.setColumns(20);
        jTextAreaDescribtion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescribtion);

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\besan\\Desktop\\Pharmacy System\\h.jpg")); // NOI18N
        jLabel7.setText("Add Drugs");

        jLabelSideEffects1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabelSideEffects1.setForeground(new java.awt.Color(0, 153, 153));
        jLabelSideEffects1.setText("Body Organs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelSideEffects)
                            .addComponent(jLabelAlternative)
                            .addComponent(jLabelSideEffects1))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelDescAndComp)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName)
                            .addComponent(jTextFieldAlternative)
                            .addComponent(jTextFieldSideEffects)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jTextFieldBodyOrgans))
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAlternative)
                    .addComponent(jTextFieldAlternative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSideEffects)
                    .addComponent(jTextFieldSideEffects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSideEffects1)
                    .addComponent(jTextFieldBodyOrgans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelDescAndComp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonAddDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDrugActionPerformed
        if(" ".equals(jTextFieldName.getText()) && " ".equals(jTextFieldAlternative.getText())&&" ".equals(jTextFieldSideEffects.getText())&&" ".equals(jTextAreaDescribtion.getText())&&" ".equals(jTextFieldBodyOrgans.getText())){
                JOptionPane.showMessageDialog(null, "must filled all fields");
        }else{
       
        Drugs drugs = new Drugs();
        drugs.setName(jTextFieldName.getText());
        drugs.setAlternativeMedicine(jTextFieldAlternative.getText());
        drugs.setDescriptionAndComposition(jTextAreaDescribtion.getText());
        drugs.setSideEffects(jTextFieldSideEffects.getText());
        drugs.setBodyOrgans(jTextFieldBodyOrgans.getText());

         ConnectionMaker cm = new ConnectionMaker();
         cm.add0(drugs);
        jTextFieldName.setText("");jTextFieldAlternative.setText("");jTextAreaDescribtion.setText("");jTextFieldSideEffects.setText("");jTextFieldBodyOrgans.setText("");
             
            
                JOptionPane.showMessageDialog(null, "added successfully");
        }  
    }//GEN-LAST:event_jButtonAddDrugActionPerformed
     
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDrug;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelAlternative;
    private javax.swing.JLabel jLabelDescAndComp;
    private javax.swing.JLabel jLabelSideEffects;
    private javax.swing.JLabel jLabelSideEffects1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescribtion;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldAlternative;
    private javax.swing.JTextField jTextFieldBodyOrgans;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSideEffects;
    // End of variables declaration//GEN-END:variables
}
