/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.myframes;

import bodyOrgans.Appliances;
import bodyOrgans.DigestiveSystem;

/**
 *
 * @author besan
 */
public class ClassifiesDrugs extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClassifiesDrugs
     */
    public ClassifiesDrugs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alternativeMed1 = new interfaces.myframes.AlternativeMed();
        jLabel8 = new javax.swing.JLabel();
        jLabelNameOfDrugs = new javax.swing.JLabel();
        jTextFieldNameDrugs = new javax.swing.JTextField();
        jLabel = new javax.swing.JLabel();
        jButtonShow = new javax.swing.JButton();
        jLabelResult = new javax.swing.JLabel();

        alternativeMed1.setVisible(true);

        setClosable(true);
        setTitle("Classification of Drugs");

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\besan\\Desktop\\Pharmacy System\\h.jpg")); // NOI18N
        jLabel8.setText("Classification of Drugs");

        jLabelNameOfDrugs.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNameOfDrugs.setForeground(new java.awt.Color(0, 153, 153));
        jLabelNameOfDrugs.setText("Enter Name of drug");

        jLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel.setForeground(new java.awt.Color(0, 153, 153));
        jLabel.setText("This medicine is continued for the   ");

        jButtonShow.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jButtonShow.setForeground(new java.awt.Color(0, 0, 153));
        jButtonShow.setText("Search");
        jButtonShow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 51)));
        jButtonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowActionPerformed(evt);
            }
        });

        jLabelResult.setText("           ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelResult))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNameOfDrugs)
                                .addGap(46, 46, 46)
                                .addComponent(jTextFieldNameDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(73, 73, 73))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNameDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNameOfDrugs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResult))
                .addGap(29, 29, 29)
                .addComponent(jButtonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowActionPerformed
        
        Appliances digestive = new DigestiveSystem();
        String res = jTextFieldNameDrugs.getText();
        String s = digestive.retriveNameOfOrgansBody(res);
        jLabelResult.setText(s);
       
    }//GEN-LAST:event_jButtonShowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private interfaces.myframes.AlternativeMed alternativeMed1;
    private javax.swing.JButton jButtonShow;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNameOfDrugs;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JTextField jTextFieldNameDrugs;
    // End of variables declaration//GEN-END:variables
}
