/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.myframes;

import database.ConnectionMaker;
import drugs.Drugs;

/**
 *
 * @author besan
 */
public class Contradictions extends javax.swing.JInternalFrame {

    /**
     * Creates new form Contradictions
     */
    public Contradictions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelNameOfDrug = new javax.swing.JLabel();
        jTextFieldNameOfDrug1 = new javax.swing.JTextField();
        jLabelAlternative = new javax.swing.JLabel();
        jButtonShow = new javax.swing.JButton();
        jLabelNameOfDrug1 = new javax.swing.JLabel();
        jLabelNameOfDrug2 = new javax.swing.JLabel();
        jLabelNameOfDrug3 = new javax.swing.JLabel();
        jTextFieldNameOfDrug2 = new javax.swing.JTextField();
        jTextFieldNameOfDrug4 = new javax.swing.JTextField();
        jTextFieldNameOfDrug3 = new javax.swing.JTextField();

        jLabel8.setBackground(new java.awt.Color(255, 255, 204));
        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\besan\\Desktop\\Pharmacy System\\h.jpg")); // NOI18N
        jLabel8.setText("Alternative Medicine");

        setClosable(true);
        setTitle("Contradictions");

        jLabel9.setBackground(new java.awt.Color(255, 255, 204));
        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\besan\\Desktop\\Pharmacy System\\h.jpg")); // NOI18N
        jLabel9.setText("Contradictions between drugs");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabelNameOfDrug.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNameOfDrug.setForeground(new java.awt.Color(0, 153, 153));
        jLabelNameOfDrug.setText("Enter Name of drug1");

        jLabelAlternative.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAlternative.setForeground(new java.awt.Color(0, 153, 153));
        jLabelAlternative.setText("Drug contrary to this drug is");

        jButtonShow.setFont(new java.awt.Font("Lucida Calligraphy", 0, 11)); // NOI18N
        jButtonShow.setForeground(new java.awt.Color(0, 0, 153));
        jButtonShow.setText("scan");
        jButtonShow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 51), new java.awt.Color(255, 255, 51)));
        jButtonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowActionPerformed(evt);
            }
        });

        jLabelNameOfDrug1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNameOfDrug1.setForeground(new java.awt.Color(0, 153, 153));
        jLabelNameOfDrug1.setText("Enter Name of drug2");

        jLabelNameOfDrug2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNameOfDrug2.setForeground(new java.awt.Color(0, 153, 153));
        jLabelNameOfDrug2.setText("Enter Name of drug3");

        jLabelNameOfDrug3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNameOfDrug3.setForeground(new java.awt.Color(0, 153, 153));
        jLabelNameOfDrug3.setText("Enter Name of drug4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNameOfDrug1)
                                    .addComponent(jLabelNameOfDrug)
                                    .addComponent(jLabelNameOfDrug2)
                                    .addComponent(jLabelNameOfDrug3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabelAlternative)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNameOfDrug1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNameOfDrug3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNameOfDrug2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNameOfDrug4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNameOfDrug, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNameOfDrug1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameOfDrug1)
                    .addComponent(jTextFieldNameOfDrug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNameOfDrug3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNameOfDrug2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNameOfDrug4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNameOfDrug3))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAlternative)
                        .addGap(49, 49, 49)))
                .addComponent(jButtonShow, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowActionPerformed
        String d1 = jTextFieldNameOfDrug1.getText();
        String d2 = jTextFieldNameOfDrug2.getText();
        String d3 = jTextFieldNameOfDrug3.getText();
        String d4 = jTextFieldNameOfDrug4.getText();

        ConnectionMaker cm = new ConnectionMaker();
        String s = cm.showingContradictions0();
        System.out.println(s);
        /*
        if(s.equals(d1)){
               
               jTextArea1.append("found contradiction between "+s);

        }else{
               jTextArea1.append("no contradiction");
        }        
        */
    }//GEN-LAST:event_jButtonShowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonShow;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAlternative;
    private javax.swing.JLabel jLabelNameOfDrug;
    private javax.swing.JLabel jLabelNameOfDrug1;
    private javax.swing.JLabel jLabelNameOfDrug2;
    private javax.swing.JLabel jLabelNameOfDrug3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNameOfDrug1;
    private javax.swing.JTextField jTextFieldNameOfDrug2;
    private javax.swing.JTextField jTextFieldNameOfDrug3;
    private javax.swing.JTextField jTextFieldNameOfDrug4;
    // End of variables declaration//GEN-END:variables
}
